require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: disable
  TargetRubyVersion: 3.1
  Exclude:
    - bin/*
    - active_graphql.gemspec
    - Rakefile

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Metrics/ClassLength:
  Exclude:
    - spec/**/*_spec.rb

Metrics/LineLength:
  Enabled: true
  Max: 120


Metrics/ModuleLength:
  Exclude:
    - spec/**/*_spec.rb

Naming/MethodParameterName:
  AllowedNames:
    - 'to'
    - 'at'
    - 'on'
    - 'id'
    - 'in'
    - 'as'

RSpec/NestedGroups:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - spec/**/*_spec.rb
RSpec/MultipleMemoizedHelpers:
  Max: 10
